AWSTemplateFormatVersion: "2010-09-09"
Description: Base Template to create a VPC

Conditions:
  AZ3NotPresent:
    Fn::Equals:
      - Ref: AWS::Region
      - ap-northeast-2
  AZ3Present:
    Fn::Not:
      - Fn::Equals:
          - Ref: AWS::Region
          - ap-northeast-2

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 172.30.0.0/16
      EnableDnsSupport: 'true'
      EnableDnsHostnames: 'true'
      Tags:
        - Key: Name
          Value: "Topic Modeling"
        - Key: StackId
          Value:
            Fn::Sub: "${AWS::StackId}"
        - Key: Stack
          Value:
            Fn::Sub: "${AWS::Region}-${AWS::StackName}"
        - Key: Application
          Value: TopicModelingApplication

  VPCS3Endpoint:
    Type: AWS::EC2::VPCEndpoint
    DependsOn:
      - VPC
    Properties:
      RouteTableIds:
        - Ref: PublicRouteTable
      ServiceName:
        Fn::Join:
          - ''
          - - com.amazonaws.
            - Ref: AWS::Region
            - ".s3"
      VpcId:
        Ref: VPC
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal: "*"
            Action:
              - s3:*
            Resource:
              - "*"

  NeptuneClientSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId:
        Ref: VPC
      GroupDescription: Allow access to connect to neptune
      Tags:
        - Key: Name
          Value: "NeptuneClientSG"
        - Key: StackId
          Value:
            Fn::Sub: "${AWS::StackId}"
        - Key: Stack
          Value:
            Fn::Sub: "${AWS::Region}-${AWS::StackName}"
        - Key: Application
          Value: TopicModelingApplication

  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:
        Ref: VPC
    DependsOn:
      - VPC

  IGW:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: "Topic Modeling IGW"
        - Key: StackId
          Value:
            Fn::Sub: "${AWS::StackId}"
        - Key: Stack
          Value:
            Fn::Sub: "${AWS::Region}-${AWS::StackName}"
        - Key: Application
          Value: TopicModelingApplication

  IGWAtt:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId:
        Ref: IGW
      VpcId:
        Ref: VPC
    DependsOn:
      - VPC
      - IGW

  PublicRoute:
    Type: AWS::EC2::Route
    Properties:
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId:
        Ref: IGW
      RouteTableId:
        Ref: PublicRouteTable
    DependsOn:
      - IGWAtt

  Subnet1:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: 172.30.1.0/24
      MapPublicIpOnLaunch: 'true'
      VpcId:
        Ref: VPC
      AvailabilityZone:
        Fn::Select:
          - 0
          - Fn::GetAZs: ''
      Tags:
        - Key: Name
          Value: pub-subnet-1-topic-modeler

  Subnet2:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: 172.30.2.0/24
      VpcId:
        Ref: VPC
      AvailabilityZone:
        Fn::Select:
          - 1
          - Fn::GetAZs: ''
      Tags:
        - Key: Name
          Value: pub-subnet-2-topic-modeler

  Subnet3:
    Type: AWS::EC2::Subnet
    Condition: AZ3Present
    Properties:
      CidrBlock: 172.30.3.0/24
      VpcId:
        Ref: VPC
      AvailabilityZone:
        Fn::Select:
          - 2
          - Fn::GetAZs: ''
      Tags:
        - Key: Name
          Value: pub-subnet-3-topic-modeler

  SubnetRTAssociation1:
    Type: AWS::EC2::SubnetRouteTableAssociation
    DependsOn:
      - Subnet1
      - PublicRouteTable
    Properties:
      RouteTableId:
        Ref: PublicRouteTable
      SubnetId:
        Ref: Subnet1

  SubnetRTAssociation2:
    Type: AWS::EC2::SubnetRouteTableAssociation
    DependsOn:
      - Subnet2
      - PublicRouteTable
    Properties:
      RouteTableId:
        Ref: PublicRouteTable
      SubnetId:
        Ref: Subnet2

  SubnetRTAssociation3:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Condition: AZ3Present
    DependsOn:
      - Subnet3
      - PublicRouteTable
    Properties:
      RouteTableId:
        Ref: PublicRouteTable
      SubnetId:
        Ref: Subnet3

Outputs:

  PublicSubnet1:
    Description: Subnet Id
    Value:
      Ref: Subnet1
  PublicSubnet2:
    Description: Subnet Id
    Value:
      Ref: Subnet2
  PublicSubnet3:
    Condition: AZ3Present
    Description: Subnet Id
    Value:
      Ref: Subnet3
  VPC:
    Description: VPC
    Value:
      Ref: VPC
  NeptuneClientSG:
    Description: Neptune client Security Group
    Value:
      Ref: NeptuneClientSG
  InternetGateway:
    Description: 'Neptune InternetGateway '
    Value:
      Ref: IGW
